version: "3"

services:
  magento:
    image: registry.gitlab.com/magebinary/docker-opensource-ecommerce:magento-2.4.2-php-7.4
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db
      - es
    ports:
      - "80:80"
    env_file:
      - default.env
    volumes:
      - .:/var/www/html/app/code/Latitude/Payment
      - .docker/tests/_output:/var/www/html/dev/tests/acceptance/tests/_output/
  db:
    image: mysql:5.7
    ports:
      - "3306"
    env_file:
      - default.env
  es:
    image: magento/magento-cloud-docker-elasticsearch:7.9-1.2.2
    ports:
        - "9200"
        - "9300"