<?php
$_helper    = $this->helper('Latitude\Payment\Helper\Config');
?>
    <div class="latitudepayments-popup">
        <div class="latitude-icon <?php echo ($block->displayIconInMobile('latitudepay')== 0? 'hide--m' : '') ?>" >
            <span class="latitudepayments-popup__installment-text">
                <img class="lpay_snippet" src="<?=/* @escapeNotVerified */ $block->getSnippetImage() ?>" alt="LatitudePay" style="cursor: pointer;">
            </span>
        </div>
    </div>

<script type="text/x-magento-init">
    {
        "*": {
            "paymentOptionPopup": {
                "utilJs" : "<?= $block->getUtilJs();?>"
            }
        }
    }

</script>

